apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: fund-transfer
  description: Create fund transfer from Endpoint Bank to another
  tags:
    - fundtransfer
    - banking
    - api
    - team:apim
  links:
    - url: https://github.com/chuwong35122/backstage-demo/blob/main/open-api/fund-transfer.yaml
      title: Github repo
      icon: github
spec:
  type: openapi
  lifecycle: production
  owner: external-gw
  system: fund-transfer
  apiProvidedBy:
    - oauth-2.0
  definition:
    $text: ../open-api/fund-transfer.yaml
