apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore-api
  description: Get/Update/Create/Delete pet information
  tags:
    - team:pet
    - internal
    - petstore
    - api
  links:
    - url: https://github.com/chuwong35122/backstage-demo/blob/main/open-api/petstore.yaml
      title: Github repo
      icon: github
spec:
  type: openapi
  lifecycle: production
  owner: internal-gw
  system: cat-migration
  definition:
    $text: ../open-api/petstore.yaml
  apiProvidedBy:
    - oauth-2.0
