apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: slip-verification-api
  description: Verify slip playment from ACME corp
  tags:
    - slip-verfication-api
    - sv-1234
  links:
    - url: https://github.com/chuwong35122/backstage-demo/blob/main/catalog-info/open-api/slip-verification.yaml
      title: Github repo
      icon: github
spec:
  type: openapi
  lifecycle: production
  owner: apim
  domain: external-gw
  system: a-api
  definition:
    $text: ../open-api/slip-verification.yaml
