---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: payment
  description: Payment domain of the ACME company.
spec:
  owner: acme
  subdomainOf: acme
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: examples
spec:
  owner: guests
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: authentication
  description: Authentication system for external gateway between for external users.
spec:
  owner: apim
  domain: external-gw
  dependsOn:
    - resource:default/database
    - resource:default/apigee
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: slip-verification
  description: Slip verification system for verifying slip payment from ACME Corp.
spec:
  owner: apim
  domain: external-gw
  dependsOn:
    - resource:default/database
    - resource:default/apigee
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: fund-transfer
  description: Fund transfer system for transferring funds between accounts.
spec:
  owner: apim
  domain: external-gw
  dependsOn:
    - resource:default/database
    - resource:default/apigee
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: fraud-detection
  description: Fraud detection system for detecting fraudulent activities between transaction.
spec:
  owner: channel
  domain: external-gw
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: credit-scoring
  description: Credit scoring system for scoring credit of customers.
spec:
  owner: leasing
  domain: internal-gw
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: apigee
  description: Google's API management gateway.
spec:
  type: kubernetes-cluster
  owner: payment
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: database
  description: Payment database for storing payment information.
spec:
  type: database
  owner: payment
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-website
spec:
  type: website
  lifecycle: experimental
  owner: guests
  system: examples
  providesApis: [example-grpc-api]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: example-grpc-api
spec:
  type: grpc
  lifecycle: experimental
  owner: guests
  system: examples
  definition: |
    syntax = "proto3";

    service Exampler {
      rpc Example (ExampleMessage) returns (ExampleMessage) {};
    }

    message ExampleMessage {
      string example = 1;
    };
