---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: payment
  description: Payment domain of the ACME company.
spec:
  owner: acme
  subdomainOf: acme
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: examples
spec:
  owner: guests
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: authentication
spec:
  owner: apim
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: slip-verification
spec:
  owner: apim
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: fund-transfer
spec:
  owner: apim
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: fraud-detection
spec:
  owner: channel
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: credit-scoring
spec:
  owner: leasing
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-website
spec:
  type: website
  lifecycle: experimental
  owner: guests
  system: examples
  providesApis: [example-grpc-api]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: example-grpc-api
spec:
  type: grpc
  lifecycle: experimental
  owner: guests
  system: examples
  definition: |
    syntax = "proto3";

    service Exampler {
      rpc Example (ExampleMessage) returns (ExampleMessage) {};
    }

    message ExampleMessage {
      string example = 1;
    };
