# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
# System
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: examples
spec:
  owner: guests
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: a-api
  description: OpenAPI system for managing external APIs.
spec:
  owner: apim
  domain: extenal-gw
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: creditscorer
  description: Credit scorer system for scoring credit of customers.
spec:
  owner: credit
  domain: internal-gw
---
# Resource
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: apigee
  description: Google's API management gateway.
spec:
  type: kubernetes-cluster
  owner: apim
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: database
  description: Payment database for storing payment information.
spec:
  type: database
  owner: payment
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-website
spec:
  type: website
  lifecycle: experimental
  owner: guests
  system: examples
  providesApis: [example-grpc-api]
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: authentication
  description: Authentication system for external gateway between for external users.
spec:
  owner: apim
  lifecycle: production
  system: a-api
  domain: external-gw
  type: service
  consumesApi: [oauth-2-api]
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: slip-verification-service
  description: Slip verification system for verifying slip payment from ACME Corp.
spec:
  owner: apim
  lifecycle: production
  system: a-api
  domain: external-gw
  type: service
  consumesApi: [oauth-2-api]
  providesApis: [slip-verification-api]
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fund-transfer-service
  description: Fund transfer system for transferring funds between accounts.
spec:
  owner: apim
  lifecycle: production
  domain: external-gw
  type: service
  system: a-api
  consumesApi: [oauth-2-api]
  providesApis: [fund-transfer-api]
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fraud-detection-service
  description: Fraud detection system for detecting fraudulent activities between transaction.
spec:
  owner: channel
  lifecycle: production
  domain: internal-gw
  type: service
  system: creditscorer
  consumesApi: [oauth-2-api]
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: credit-scoring-service
  description: Credit scoring system for scoring credit of customers.
spec:
  owner: leasing
  lifecycle: production
  domain: internal-gw
  type: service
  system: creditscorer
  consumesApi: [oauth-2-api]
  providesApi: [petstore-api]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: example-grpc-api
spec:
  type: grpc
  lifecycle: experimental
  owner: guests
  system: examples
  definition: |
    syntax = "proto3";

    service Exampler {
      rpc Example (ExampleMessage) returns (ExampleMessage) {};
    }

    message ExampleMessage {
      string example = 1;
    };
