---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []
---
################
# ACME Corp.   #
################
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: acme-corp
  description: ACME Corporation
  links:
    - url: https://acme-corp.com
      title: ACME Corporation
spec:
  type: organization
  profile:
    displayName: ACME Corp
    email: contact.acme@example.com
    picture: https://static.wikia.nocookie.net/fictionalcompanies/images/c/c2/ACME_Corporation.png/revision/latest?cb=20230628025220
  children: [payment, channel, leasing]
---
################################
### ACME Corp's Departments  ###
################################

apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: payment
  description: The payment department within ACME Corp.
spec:
  type: department
  parent: acme-corp
  children: [apim]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: channel
  description: The customer channel department within ACME Corp.
spec:
  type: department
  parent: acme-corp
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: leasing
  description: The leasing department within ACME Corp.
spec:
  type: department
  parent: acme-corp
  children: [credit]
---
################################
##### External-GW Domain  ######
################################

apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: external-gw
spec:
  type: domain
  children: []
---
################################
##### Internal-GW Domain  ######
################################

apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: internal-gw
spec:
  type: domain
  children: []
---
################################
### Team within department  ####
################################

# Team within payment
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: apim
  description: API Management team within the payment department.
spec:
  type: team
  memberOf: [payment]
---
# Team within leasing
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: credit
  description: Credit scoring team within the leasing department.
spec:
  type: team
  memberOf: [leasing]
---
# Apim Team member
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: B.P.
spec:
  type: user
  memberOf: [apim, acme-corp, payment]
---
# Apim Team member
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: C.A.
spec:
  type: user
  memberOf: [apim, acme-corp, payment]
---
# Apim Team member
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: L.P.
spec:
  type: user
  memberOf: [leasing, acme-corp, credit]
---

